<?php /** @var Orra\Videos\Block\Videos  $block  */ ?>
<?php  $videoData = $block->getVideos();?>
  <div class="video-sec">
      <?php foreach ($videoData as $videoKey => $videoValue) {?>
        <div class="video_left">
          <video width="100%" height="600" controls="controls">
            <source src="<?= $videoValue->getVideoUrl() ?>" type="video/mp4">
            <source src="<?= $videoValue->getVideoUrl() ?>" type="video/ogg">
            <source src="<?= $videoValue->getVideoUrl() ?>" type="video/webm">
          </video>
        <?php } ?>
      </div>
      <div class="video-right">
          <?= $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('homepage_right_image')
          ->toHtml();?>
      </div>
  </div>
  