<?php

?>
<?php
/**
 * @var \Magento\Catalog\Block\Product\View $block
 * @var \MGS\BuyNow\ViewModel\BuyNow $viewModel
 */
$viewModel = $block->getViewModel();
$buttonTitle = $viewModel->getButtonTitle();
?>
<div class="mageprince-buynow">
    <button type="submit"
            title="<?= $block->escapeHtml(__($buttonTitle)) ?>"
            class="action primary mageprince-buy-now-btn"
            data-mage-init='{"MGS_BuyNow/js/buy-now-view": {}}'>
        <span><?= $block->escapeHtml(__($buttonTitle)) ?></span>
    </button>
</div>
