<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>

<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<meta itemprop="name" content="<?=$_helper->productAttribute($block->getProduct(), $block->getProduct()->getName(), 'name')?>" />
<link itemprop="image" href="<?=$block->getProduct()->getImage()?>" />
<h1 class="product-name"><?php echo $_helper->productAttribute($block->getProduct(), $block->getProduct()->getName(), 'name') ?></h1>
