<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
$_description = $block->getCurrentCategory()->getDescription();
$html = $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description');
?>
<?php if ($_description) :?>
    <div class="category-description">
        <?php echo $html; ?>
    </div>
<?php endif; ?>
